# Generated by Django 4.1.7 on 2023-03-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation_app', '0003_student_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
