# Generated by Django 4.1.7 on 2023-03-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation_app', '0004_alter_student_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.BigIntegerField(blank=True),
        ),
    ]
