# Generated by Django 4.1.7 on 2023-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=50)),
                ('days', models.PositiveIntegerField()),
                ('salary', models.FloatField(default=300)),
            ],
        ),
    ]
