# Generated by Django 4.1.7 on 2023-05-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001D6A8073740>', max_length=200),
        ),
    ]
