# Generated by Django 4.1.7 on 2023-05-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_user_otp_remove_user_uid_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
