# Generated by Django 4.1.7 on 2023-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001E2FA56A480>', max_length=200),
        ),
    ]
